#!/usr/bin/env python3
"""lessons.py — the builder's lessons journal (stdlib only).

The feedback loop between the owner's MANUAL interventions and the next round of
pipeline improvements. Every time a human has to step in and correct the
tooling's output — a timing nudge on the denmoku, a curated word-clip swap,
a lexicon pin, a backlog resolution — the tool that did it appends one entry
here. "Work on improvements" starts by READING the rendered LESSONS.md:
recurring manual fixes are exactly what the pipeline should learn to do
itself.

Store: builds/lessons.jsonl — append-only, one JSON object per line:
  {ts (epoch int), kind, song, summary, detail, source}
kind ∈ manual | timing | word | lexicon | backlog. Committed (not gitignored):
the journal IS the institutional memory.

Subcommands:
  add     --kind K --song S --summary "..." [--detail ..] [--source manual]
  render  regenerate tools/songcraft/LESSONS.md (idempotent — content depends
          only on the journal; grouped by kind, newest first)
  list    [--kind K]   show entries as a table

The instrumented writers (timing_edit.py set/adopt, install_word.py,
manaoke_build.py lexicon add, backlog.py resolve) call journal() directly —
append + re-render in one step. They wrap the call in try/except so a journal
failure never breaks the edit itself.
"""
import argparse, json, sys, time
from pathlib import Path

HERE = Path(__file__).resolve().parent          # tools/songcraft
JOURNAL = HERE / 'builds' / 'lessons.jsonl'
MD = HERE / 'LESSONS.md'
KINDS = ('manual', 'timing', 'word', 'lexicon', 'backlog')

KIND_BLURB = {
    'manual':  'Hand-noted lessons — things a human learned the hard way that no tool journals on its own.',
    'timing':  'Line-timing nudges/adopts via `timing_edit.py` — each one is a place the aligner was wrong.',
    'word':    'Curated word-clip installs via `install_word.py` — each one is a clip TTS got wrong.',
    'lexicon': 'Site-wide pronunciation pins via `manaoke_build.py lexicon add` — words TTS must never voice again.',
    'backlog': 'Backlog resolutions via `backlog.py resolve` — how known issues actually got closed.',
}

# ── journal I/O ────────────────────────────────────────────────────────────
def load():
    """Every parseable entry, journal order. A corrupt line is skipped, never
    fatal — the journal is best-effort infrastructure."""
    if not JOURNAL.exists():
        return []
    out = []
    for ln in JOURNAL.read_text().splitlines():
        ln = ln.strip()
        if not ln:
            continue
        try:
            out.append(json.loads(ln))
        except json.JSONDecodeError:
            continue
    return out


def journal(kind, song, summary, detail='', source=''):
    """THE write path: append one entry + re-render LESSONS.md. The
    instrumented tools call this (wrapped in try/except on their side)."""
    entry = {'ts': int(time.time()), 'kind': kind, 'song': song or '',
             'summary': summary, 'detail': detail or '', 'source': source or ''}
    JOURNAL.parent.mkdir(parents=True, exist_ok=True)
    with open(JOURNAL, 'a', encoding='utf-8') as f:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')
    render()
    return entry


# ── render (idempotent: output depends only on the journal) ────────────────
_MD_HEADER = """\
# LESSONS — what manual interventions taught the pipeline

> Generated by `lessons.py render` from `builds/lessons.jsonl`. Do not edit by
> hand — append with `lessons.py add`; the manual-edit tools (`timing_edit.py`,
> `install_word.py`, `manaoke_build.py lexicon add`, `backlog.py resolve`)
> journal automatically.

**What this file is FOR: read it BEFORE working on pipeline improvements**
("work on improvements" / "make it better" / "what have we learned"). Every
entry below is a place where a human had to step in and correct the tooling's
output. One entry is an anecdote; a recurring pattern is the improvement
backlog's raw material — if the same kind of manual fix keeps appearing, the
pipeline should learn to make it unnecessary. Pair with
`backlog.py list --status open` for the known-issue side of the picture.
"""


def _day(ts):
    return time.strftime('%Y-%m-%d', time.localtime(int(ts or 0)))


def render():
    entries = load()
    lines = [_MD_HEADER]
    total = 0
    for kind in KINDS + tuple(sorted({e.get('kind', '?') for e in entries} - set(KINDS))):
        group = [e for e in entries if e.get('kind') == kind]
        if not group:
            continue
        total += len(group)
        group.sort(key=lambda e: e.get('ts', 0), reverse=True)   # newest first
        lines.append(f"## {kind} — {len(group)} entr{'y' if len(group) == 1 else 'ies'}\n")
        if kind in KIND_BLURB:
            lines.append(KIND_BLURB[kind] + '\n')
        for e in group:
            head = f"- **{_day(e.get('ts'))}**"
            if e.get('song'):
                head += f" · {e['song']}"
            if e.get('source'):
                head += f" · `{e['source']}`"
            lines.append(f"{head} — {e.get('summary', '')}")
            if e.get('detail'):
                lines.append(f"  - {e['detail']}")
        lines.append('')
    if not total:
        lines.append('*(journal empty — no lessons yet)*\n')
    MD.write_text('\n'.join(lines))
    return total


# ── CLI ────────────────────────────────────────────────────────────────────
def cmd_add(a):
    e = journal(a.kind, a.song, a.summary, detail=a.detail, source=a.source)
    print(f"journaled [{e['kind']}] {e['song'] or '(site-wide)'}: {e['summary']}")
    print(f"rendered {MD.relative_to(HERE.parents[1])}")
    return 0


def cmd_render(a):
    n = render()
    print(f'wrote {MD.relative_to(HERE.parents[1])}  ({n} entr{"y" if n == 1 else "ies"})')
    return 0


def cmd_list(a):
    entries = [e for e in load() if not a.kind or e.get('kind') == a.kind]
    if not entries:
        print('(no matching lessons)')
        return 0
    entries.sort(key=lambda e: e.get('ts', 0), reverse=True)
    w = dict(day=10, kind=7, song=18)
    hdr = f'{"date":<{w["day"]}} {"kind":<{w["kind"]}} {"song":<{w["song"]}} summary'
    print(hdr)
    print('-' * len(hdr))
    for e in entries:
        print(f"{_day(e.get('ts')):<{w['day']}} {e.get('kind', '')[:w['kind']]:<{w['kind']}} "
              f"{e.get('song', '')[:w['song']]:<{w['song']}} {e.get('summary', '')}")
    print(f'\n{len(entries)} entr{"y" if len(entries) == 1 else "ies"}')
    return 0


def main():
    ap = argparse.ArgumentParser(description="The builder's lessons journal.")
    sub = ap.add_subparsers(dest='cmd', required=True)

    p = sub.add_parser('add', help='journal one lesson (appends + re-renders)')
    p.add_argument('--kind', required=True, choices=KINDS)
    p.add_argument('--song', default='', help='song key, or empty for site-wide')
    p.add_argument('--summary', required=True)
    p.add_argument('--detail', default='')
    p.add_argument('--source', default='manual',
                   help='which tool/context journaled this (default: manual)')
    p.set_defaults(fn=cmd_add)

    p = sub.add_parser('render', help='regenerate LESSONS.md from the journal')
    p.set_defaults(fn=cmd_render)

    p = sub.add_parser('list', help='show entries as a table')
    p.add_argument('--kind', choices=KINDS)
    p.set_defaults(fn=cmd_list)

    a = ap.parse_args()
    return a.fn(a)


if __name__ == '__main__':
    sys.exit(main())
