#!/usr/bin/env python3
"""Generate TTS word audio MP3s from a tts_manifest.json.

Usage: python3 tools/generate_tts.py songs/silhouette/tts_manifest.json
Output: ./tts_output/Audio Lyrics/*.mp3

The manifest is auto-generated by build_song.py alongside the data.json.
"""

import json, sys, os, base64, time, requests

def load_key():
    for path in [".env", os.path.join(os.path.dirname(__file__), "..", ".env")]:
        if os.path.exists(path):
            with open(path) as f:
                for line in f:
                    if line.startswith("GOOGLE_TTS_KEY="):
                        return line.split("=", 1)[1].strip()
    print("ERROR: No .env file with GOOGLE_TTS_KEY found")
    sys.exit(1)

def generate_tts(text, lang, voice, rate, output_path, key):
    resp = requests.post(
        f"https://texttospeech.googleapis.com/v1/text:synthesize?key={key}",
        json={
            "input": {"text": text},
            "voice": {"languageCode": lang, "name": voice},
            "audioConfig": {"audioEncoding": "MP3", "speakingRate": rate}
        }
    )
    data = resp.json()
    if "audioContent" in data:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(base64.b64decode(data["audioContent"]))
        return True
    else:
        print(f"  ERROR: {data.get('error', {}).get('message', data)}")
        return False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 tools/generate_tts.py songs/{slug}/tts_manifest.json")
        sys.exit(1)

    manifest_path = sys.argv[1]

    # TTS language-safety gate: refuse to synthesize a manifest that would let an
    # English voice speak Japanese (or vice versa), or that's missing a clip the
    # page will try to speak. Pass --skip-safety to override (not recommended).
    if "--skip-safety" not in sys.argv:
        try:
            from validate_tts_safety import main as _validate_main
        except ImportError:
            sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
            from validate_tts_safety import main as _validate_main
        _saved_argv = sys.argv
        sys.argv = ["validate_tts_safety", manifest_path]
        rc = _validate_main()
        sys.argv = _saved_argv
        if rc != 0:
            print("\nABORTED: TTS safety check failed. Fix the manifest or pass --skip-safety.")
            sys.exit(rc)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    key = load_key()
    out_dir = os.path.join("tts_output", "Audio Lyrics")
    os.makedirs(out_dir, exist_ok=True)

    voices = {
        "ja-JP": ("ja-JP-Neural2-B", 0.85),
        "en-US": ("en-US-Neural2-J", 1.0),
        "es-US": ("es-US-Neural2-A", 0.9),
    }

    total = len(manifest)
    success = 0
    errors = 0

    print(f"Generating {total} TTS clips...\n")

    for i, (lang, text, speak_text, filename) in enumerate(manifest, 1):
        voice, rate = voices[lang]
        out_path = os.path.join(out_dir, filename)

        if os.path.exists(out_path):
            print(f"  [{i}/{total}] SKIP (exists): {filename}")
            success += 1
            continue

        tag = "JP" if lang == "ja-JP" else "ES" if lang == "es-US" else "EN"
        label = speak_text[:50] + ("..." if len(speak_text) > 50 else "")
        print(f"  [{i}/{total}] {tag}: {label}")

        if generate_tts(speak_text, lang, voice, rate, out_path, key):
            success += 1
        else:
            errors += 1

        # Rate limit: ~10 requests/sec is safe
        if i % 10 == 0:
            time.sleep(1)

    print(f"\n✓ {success}/{total} generated, {errors} errors")
    print(f"  Output: {out_dir}/")
